name: Build and deploy ASP.Net Core apps to Azure Web Apps - ChineseStoryGenerator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore ./ChineseStoryGenerator.sln

      - name: Build with dotnet
        run: dotnet build ./ChineseStoryGenerator.sln --configuration Release --no-restore

      - name: Publish WASM app
        run: dotnet publish ./ChineseStoryGenerator/ChineseStoryGenerator.csproj -c Release --no-build --output './publish-wasm'

      - name: Publish API
        run: dotnet publish ./ChineseStoryHome.Api/ChineseStoryHome.Api.csproj -c Release --no-build --output './publish-api'

      - name: Deploy WASM app
        uses: azure/webapps-deploy@v3
        with:
          app-name: ChineseStoryGenerator
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D2A8DF5E99094649B97D6A83E1839664 }}
          package: './publish-wasm'

      - name: Deploy API
        uses: azure/webapps-deploy@v3
        with:
          app-name: williamapi
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F28D5C1AB88C4C75AF73B43ECD1E5AC0 }}
          package: './publish-api'
